### ISSUE TITLE
longitude and latitude instead of lat and lon in attributes?

### ISSUE THREAD

**Issue by canedje** [leeuwte/home-assistant-p2000#1]
This works very nice.
A lot of information.
Thanks.

As far as I now, HA is using latitude and longitude instead of lat and lon.
So the location is not possible to show in a map at HA.
IS it possible to change lat and lon in latitude and longitude?

EDIT:
I did found a workaround making a template with the right format:

```
    p2000_tracker:
       friendly_name: "P 2000 position"
       value_template: "{{ state_attr('sensor.p2000', 'id') }}"
       attribute_templates:
         latitude: "{{ state_attr('sensor.p2000', 'lat') }}"
         longitude: "{{ state_attr('sensor.p2000', 'lon') }}"

```
![image](https://user-images.githubusercontent.com/23150947/143885011-0755b5ad-c105-49c3-bb58-779cada411e1.png)
