### ISSUE TITLE
This is a good replacement for the p2000 integration beacause of loss lon/lat

### ISSUE THREAD

**Issue by ArnolddeBolster** [leeuwte/home-assistant-p2000#11]
Hi,
@leeuwte, hopefully you would provide us with some extra filters now the othet HACS p2000 integration doesn't provide lon/lat anymore.

The feed you use does.

If filter "dienst" is possible to integrate then I can show items by discipline.
Or/and it would be nice if your code is seperated by "dienst" with the right icons mdi:fire-truck, mdi:ambulance, mdi:helicopter and mdi:car-emergency.

This p2000 integration is very useful for people who do not want to use extra hardware as suggested by the HACS integration

**Comment by leeuwte** [comment]
Thnx for your message. It's been a while since I worked on this integration. I'll try to find some time to see what I can do!

**Comment by ArnolddeBolster** [comment]
That good news.
Hopefully you can get this as result on logbook card:
![Schermafbeelding 2024-04-07 134204](https://github.com/leeuwte/home-assistant-p2000/assets/71195708/c0f7b945-4cd8-4cf1-81c8-af239b15ac73)
and this for seperated entities (dienst) with their lon/lat to plot on 1 map:
![image](https://github.com/leeuwte/home-assistant-p2000/assets/71195708/9946d1ce-2476-4cca-b9cf-e30fc67af22f)

good luck and many thanks in advance !!!!

**Comment by EdwinKort** [comment]
That would be nice.

**Comment by ArnolddeBolster** [comment]
@leeuwte Hi Benny, is there any news on this integration ?

**Comment by leeuwte** [comment]
Would something like this work for you?

```
sensor:
  - platform: p2000
    name: Brandweer
    icon: mdi:fire-truck
    gemeenten:
      - Zwolle
    diensten:
      - 2
  - platform: p2000
    icon: mdi:ambulance
    name: Ambulance
    gemeenten:
      - Zwolle
    diensten:
      - 3
```
    
    
<img width="530" alt="Screenshot 2024-05-22 at 20 06 52" src="https://github.com/leeuwte/home-assistant-p2000/assets/2683564/6058f1ab-d235-41c0-ac5e-02127267e0fb">
