### ISSUE TITLE
No valid option

### ISSUE THREAD

**Issue by thoompje** [leeuwte/home-assistant-p2000#16]
Hello,

I am trying to add the sensor in my configuration.yaml. But the platform gives me an error back that the option regios is not an valid option... Algo get this at the icon option.

```
sensor:

  - platform: p2000
    name: P2000
    icon: mdi:fire-truck
    regios:
      - 19

```

```
Logger: homeassistant.config
Source: config.py:1298
First occurred: 11:47:26 AM (1 occurrences)
Last logged: 11:47:26 AM

Invalid config for 'sensor' from integration 'p2000' at configuration.yaml, line 162: 'regios' is an invalid option for 'p2000.sensor', check: regios

```

Thanks for the help! Cheers.
