### ISSUE TITLE
Filtering op plaatsnaam

### ISSUE THREAD

**Issue by jan-dewit** [leeuwte/home-assistant-p2000#7]
Het filteren op plaatsnaam lijkt niet goed te functioneren als er in de plaatsnaam bijvoorbeeld een - voorkomt. Met bijvoorbeeld Sprang-Capelle of Nieuw-Amsterdam.

Mijn configuratie is nu als volgt (als test), en de sensor wordt continu geupdate met allemaal andere plaatsnamen.

````
  - platform: p2000
    name: p2000
    gemeenten:
      - Sprang-Capelle

``````
